[Core]
Plugins = [
  "@openledcontrol/raspberrypi",
  "@openledcontrol/rest"
]

[Core.LedStrip]
Length = 60

[REST]
Port = 8081

[RaspberryPi]
ColorOrder = "grb"
MaximumBrightness = 255
DMA = 10
GPIO = 18
