[Core]
Plugins = [
#  "@openledcontrol/rest",
#  "@openledcontrol/gitlab",
#  "@openledcontrol/raspberrypi"
]

[Core.LedStrip]
Length = 60
Reverse = true

[REST]
Port = 8081

[RaspberryPi]
ColorOrder = "grb"
MaximumBrightness = 255
DMA = 10
GPIO = 18

[GitLab]
# Put your API token here
# Token = ""

# If your host differs from the hosted gitlab instance you need
# to specify the host here.
# Host = "https://gitlab.com"
UpdateInterval = 15000
Projects = [
  1,
  2,
  3
]
